set(CPACK_PACKAGE_NAME "airmouse")
set(CPACK_PACKAGE_VENDOR "AirMouse")
set(CPACK_PACKAGE_CONTACT "contact@zethr.us")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Webcam hand-gesture mouse")
set(CPACK_PACKAGE_DESCRIPTION
  "AirMouse turns a built-in webcam into a pointer using on-device hand tracking.")
set(CPACK_PACKAGE_VERSION "${AIRMOUSE_VERSION}")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/Zethrus/AirMouse")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_STRIP_FILES TRUE)
set(CPACK_VERBATIM_VARIABLES TRUE)
set(CPACK_PACKAGE_EXECUTABLES "airmouse;AirMouse")

if(WIN32)
  set(CPACK_GENERATOR "ZIP;WIX;NSIS")
  set(CPACK_PACKAGE_FILE_NAME "airmouse-${AIRMOUSE_VERSION}-windows-x64")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "AirMouse")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/packaging/windows/License.rtf")
  set(CPACK_WIX_UPGRADE_GUID "8F3C2A91-6B47-4E1D-9C08-2A7D4E5F6B10")
  set(CPACK_WIX_PRODUCT_GUID "*")
  set(CPACK_WIX_PROGRAM_MENU_FOLDER "AirMouse")
  set(CPACK_NSIS_DISPLAY_NAME "AirMouse")
  set(CPACK_NSIS_PACKAGE_NAME "AirMouse")
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  set(CPACK_NSIS_MODIFY_PATH ON)
  set(CPACK_NSIS_URL_INFO_ABOUT "https://github.com/Zethrus/AirMouse")
  set(CPACK_NSIS_HELP_LINK "https://github.com/Zethrus/AirMouse/issues")
  set(CPACK_NSIS_CONTACT "contact@zethr.us")
  set(CPACK_NSIS_INSTALLED_ICON_NAME "airmouse.exe")
  set(CPACK_CREATE_DESKTOP_LINKS "airmouse")
else()
  set(CPACK_GENERATOR "TGZ;DEB")
  find_program(RPMBUILD_EXECUTABLE rpmbuild)
  if(RPMBUILD_EXECUTABLE)
    list(APPEND CPACK_GENERATOR RPM)
  endif()
  set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
  set(CPACK_PACKAGE_FILE_NAME "airmouse-${AIRMOUSE_VERSION}-linux-x86_64")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
  set(CPACK_DEBIAN_FILE_NAME "airmouse_${AIRMOUSE_VERSION}_amd64.deb")
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "AirMouse <contact@zethr.us>")
  set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
  set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
  set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Zethrus/AirMouse")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
  set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
      "${CMAKE_SOURCE_DIR}/packaging/linux/postinst"
      "${CMAKE_SOURCE_DIR}/packaging/linux/postrm")
  set(CPACK_RPM_FILE_NAME "airmouse-${AIRMOUSE_VERSION}-1.x86_64.rpm")
  set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
  set(CPACK_RPM_PACKAGE_LICENSE "MIT")
  set(CPACK_RPM_PACKAGE_URL "https://github.com/Zethrus/AirMouse")
  set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE
      "${CMAKE_SOURCE_DIR}/packaging/linux/postinst")
  set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE
      "${CMAKE_SOURCE_DIR}/packaging/linux/postrm")
endif()

include(CPack)
